# Generated by Django 4.0.1 on 2022-01-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_territory', models.CharField(max_length=90, verbose_name='Карта')),
                ('scale', models.CharField(max_length=20, verbose_name='Масштаб')),
            ],
        ),
        migrations.CreateModel(
            name='PointModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_coord', models.FloatField(blank=True, verbose_name='Координата X')),
                ('y_coord', models.FloatField(blank=True, verbose_name='Координата Y')),
                ('abs_height', models.FloatField(blank=True, verbose_name='Абсолютна висота')),
            ],
        ),
        migrations.CreateModel(
            name='LineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(blank=True, verbose_name='Довжина')),
                ('elevation', models.FloatField(blank=True, verbose_name='Перевищення')),
                ('point', models.ManyToManyField(to='api.PointModel')),
            ],
        ),
        migrations.CreateModel(
            name='ChainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Назва ходу')),
                ('type', models.CharField(max_length=20, verbose_name='Тип ходу')),
                ('accuracy', models.CharField(max_length=20, verbose_name='Точність/класс ходу')),
                ('line', models.ManyToManyField(to='api.LineModel')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mapmodel', verbose_name='Карта')),
                ('point', models.ManyToManyField(to='api.PointModel')),
            ],
        ),
    ]
