# Generated by Django 4.0.1 on 2022-01-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointmodel',
            old_name='z_coord',
            new_name='x_coord',
        ),
        migrations.AlterField(
            model_name='chainmodel',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='api.mapmodel', verbose_name='Карта'),
        ),
    ]
